### PR TITLE
Client api failure handling

### PR DESCRIPTION
**Pull request by arashbahreini**

### CODE REVIEW

**Comment by N1MA** [comment]
It seems fine, just please resolve merge conflicts.

**Comment by arashbahreini** [comment]
Done. please review.

**Comment by N1MA** [comment]
It seems to be working as intended, just a couple of notes:

All the snackbar error showing codes are repetitive, why not put them inside of interceptor itself.

All messages are generic (Internal Server error, Bad request ... )  we need to elaborate, these are not enough.

Even though there are no serious errors, but there are a couple of linting errors as I was going through code. Theses kind of errors might seem negligible now but they will pile up as time goes by and make code more and more unreadable. So make sure you resolve them or add appropriate [tslint rule flags](https://palantir.github.io/tslint/usage/rule-flags/) in edge cases while explaining why you did this.

**Comment by arashbahreini** [comment]
Got it. I will resolve it and apply pull request again.

**Comment by arashbahreini** [comment]
I didn't have TsLint extension in my IDE. I added it and fix lint issues.

**Pull request merged**
