### PR TITLE
#48 crud for app instance

### PR DESCRIPTION
**Pull request by arashbahreini**

### CODE REVIEW

**Comment by AlirezaHaghshenas** [comment]
In AppManagementController, line 210:

```c#
result.Trusted_Connection = Trusted_Connection.Success ? bool.Parse(Trusted_Connection.Groups[1].Value) : false;
```
In the existing connection string, one might've written `yes` instead of `true`. The code should be able to recognize that and act accordingly.

**Comment by AlirezaHaghshenas** [comment]
The connection string is now sent to the client as part of `appInstanceInfo`, which is available to all users. This is a serious security issue. The connection string should only be visible to (very) privileged admins.

**Comment by arashbahreini** [comment]
Yes, correct but the password is hidden from the user. we can also don't send password from the server to the client. 
For more security, we should write check permission function in action/controller to don't send connection string to the client.

**Comment by AlirezaHaghshenas** [comment]
> 
> 
> Yes, correct but the password is hidden from the user. we can also don't send password from the server to the client.
> For more security, we should write check permission function in action/controller to don't send connection string to the client.

I suggest we have two different actions: one for all users to get `AppInstanceInfo`,
another for admins to get a model, maybe named `AppInstanceModel` for management.

**Pull request merged**
